### ISSUE TITLE
locales key missing from file - Cuicatec

### ISSUE THREAD

**Issue by ftyers** [divvun/kbdgen-archived#35]
I'm trying to make an android keyboard for Cuicatec:

```
fran@ipek:~/source/giellatekno/giella-core/kbdgen$ python3 -m kbdgen -t android examples/cux.yaml 
[C cli:110] locales key missing from file.
[C cli:117] You should not be seeing this error. Please report this as a bug.
[C cli:119] URL: https://github.com/divvun/kbdgen/issues/
```

The yaml file is:
```
internalName: cuicatec

displayNames:
  cux: Cuicatec
  en: Cuicatec
  es: Cuicateco 

locale: cux

modes:
  mobile-default: |
    ʼ w e r t y u i o p
    a s d f g h j k l ñ
    z x v b n m 
  mobile-shift: |
    ʼ W E R T Y U I O P 
    A S D F G H J K L Ñ
    Z X V B N M 


decimal: ','

deadKeys:
  iso-default: ["`"]
  iso-shift: ["`"]

longpress:
  A: Á À
  ʼ: q 

styles:
  tablet:
    actions:
      backspace: [1, right, fill]
      enter: [2, right, fill]
      shift: [3, both, fill]
  phone:
    actions:
      shift: [3, left, fill]
      backspace: [3, right, fill]

#targets:
#  android:
#    minimumSdk: 21

strings:
  space: gaske
  return: linnjámolsun
```
