### ISSUE TITLE
compile error linking with cc

### ISSUE THREAD

**Issue by ftyers** [divvun/kbdgen-archived#37]
```
fran@ipek:~/source/giellatekno/giella-core/kbdgen$ python3 -m kbdgen -t android examples/project-cux.yaml 
[I android:582] Getting source files from divvun/giella-ime master branch…
[I android:464] Adding 'cux' to './deps/giella-ime/app/src/main/res/values/donottranslate.xml'…
[I android:109] Updating XML strings…
[I android:538] Updating method definitions…
[I android:565] Embedding generated keyboard XML files…
[W android:276] No ZHFST files found.
[I android:331] Updating localisation values…
[W android:345] no icon supplied!
[I android:396] Building native components…
[I android:398] Building armv7-linux-androideabi architecture…
    Updating git repository `https://github.com/bbqsrc/serde-xml-rs`
  Downloaded serde_json v1.0.39
  Downloaded parking_lot v0.7.1
  Downloaded serde_derive v1.0.89
  Downloaded zip v0.5.0
  Downloaded libc v0.2.47
  Downloaded tempdir v0.3.7
  Downloaded serde v1.0.89
  Downloaded hashbrown v0.1.5
  Downloaded lazy_static v1.3.0
  Downloaded log v0.4.6
  Downloaded env_logger v0.6.1
  Downloaded fxhash v0.2.1
  Downloaded unic-ucd-common v0.9.0
  Downloaded unic-segment v0.9.0
  Downloaded byteorder v1.3.1
  Downloaded memmap v0.7.0
  Downloaded error-chain v0.12.0
  Downloaded proc-macro2 v0.4.20
  Downloaded ryu v0.2.7
  Downloaded xml-rs v0.8.0
  Downloaded quote v0.6.9
  Downloaded itoa v0.4.3
  Downloaded parking_lot_core v0.4.0
  Downloaded syn v0.15.25
  Downloaded lock_api v0.1.4
  Downloaded podio v0.1.5
  Downloaded rand v0.4.6
  Downloaded crc32fast v1.1.2
  Downloaded remove_dir_all v0.5.1
  Downloaded scopeguard v0.3.3
  Downloaded humantime v1.1.1
  Downloaded termcolor v1.0.4
  Downloaded cfg-if v0.1.6
  Downloaded unic-char-property v0.9.0
  Downloaded regex v1.0.5
  Downloaded unic-char-range v0.9.0
  Downloaded unic-ucd-segment v0.9.0
  Downloaded unic-ucd-version v0.9.0
  Downloaded unicode-xid v0.1.0
  Downloaded smallvec v0.6.5
  Downloaded rustc_version v0.2.3
  Downloaded quick-error v1.2.2
  Downloaded rand v0.6.4
  Downloaded owning_ref v0.3.3
  Downloaded unreachable v1.0.0
  Downloaded aho-corasick v0.6.9
  Downloaded utf8-ranges v1.0.2
  Downloaded thread_local v0.3.6
  Downloaded memchr v2.1.1
  Downloaded void v1.0.2
  Downloaded regex-syntax v0.6.2
  Downloaded unic-common v0.9.0
  Downloaded rand_xorshift v0.1.1
  Downloaded rand_pcg v0.1.1
  Downloaded rand_isaac v0.1.1
  Downloaded rand_core v0.3.0
  Downloaded rand_hc v0.1.0
  Downloaded rand_os v0.1.1
  Downloaded rand_chacha v0.1.1
  Downloaded semver v0.9.0
  Downloaded autocfg v0.1.1
  Downloaded stable_deref_trait v1.1.1
  Downloaded version_check v0.1.5
  Downloaded ucd-util v0.1.2
  Downloaded semver-parser v0.7.0
   Compiling semver-parser v0.7.0
   Compiling libc v0.2.47
   Compiling autocfg v0.1.1
   Compiling version_check v0.1.5
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/build/libc-ccd5fb3890d7398e/build_script_build-ccd5fb3890d7398e.build_script_build.bx6mthju-cgu.0.rcgu.o" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/build/libc-ccd5fb3890d7398e/build_script_build-ccd5fb3890d7398e.build_script_build.bx6mthju-cgu.1.rcgu.o" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/build/libc-ccd5fb3890d7398e/build_script_build-ccd5fb3890d7398e.build_script_build.bx6mthju-cgu.10.rcgu.o" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/build/libc-ccd5fb3890d7398e/build_script_build-ccd5fb3890d7398e.build_script_build.bx6mthju-cgu.11.rcgu.o" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/build/libc-ccd5fb3890d7398e/build_script_build-ccd5fb3890d7398e.build_script_build.bx6mthju-cgu.12.rcgu.o" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/build/libc-ccd5fb3890d7398e/build_script_build-ccd5fb3890d7398e.build_script_build.bx6mthju-cgu.13.rcgu.o" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/build/libc-ccd5fb3890d7398e/build_script_build-ccd5fb3890d7398e.build_script_build.bx6mthju-cgu.2.rcgu.o" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/build/libc-ccd5fb3890d7398e/build_script_build-ccd5fb3890d7398e.build_script_build.bx6mthju-cgu.3.rcgu.o" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/build/libc-ccd5fb3890d7398e/build_script_build-ccd5fb3890d7398e.build_script_build.bx6mthju-cgu.4.rcgu.o" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/build/libc-ccd5fb3890d7398e/build_script_build-ccd5fb3890d7398e.build_script_build.bx6mthju-cgu.5.rcgu.o" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/build/libc-ccd5fb3890d7398e/build_script_build-ccd5fb3890d7398e.build_script_build.bx6mthju-cgu.6.rcgu.o" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/build/libc-ccd5fb3890d7398e/build_script_build-ccd5fb3890d7398e.build_script_build.bx6mthju-cgu.7.rcgu.o" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/build/libc-ccd5fb3890d7398e/build_script_build-ccd5fb3890d7398e.build_script_build.bx6mthju-cgu.8.rcgu.o" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/build/libc-ccd5fb3890d7398e/build_script_build-ccd5fb3890d7398e.build_script_build.bx6mthju-cgu.9.rcgu.o" "-o" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/build/libc-ccd5fb3890d7398e/build_script_build-ccd5fb3890d7398e" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/build/libc-ccd5fb3890d7398e/build_script_build-ccd5fb3890d7398e.2vzib6xddo4z7vgy.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs/target/release/deps" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-79f126b09196cdf2.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-376a22c973b921f9.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-90dc619dced03db1.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-b17a16bb50dcf6e7.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-80afe56a7ca6b327.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-5e5f3cc5ac04f2f3.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-62795edc93df4274.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-2490d0c739fb5363.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-c00b11ce47d19e63.rlib" "-Wl,--end-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-a9797aba406537c8.rlib" "-Wl,-Bdynamic" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: /usr/lib/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld: error: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o: unsupported reloc 42 against global symbol __libc_csu_fini
          /usr/lib/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld: error: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o: unsupported reloc 42 against global symbol __libc_csu_init
          /usr/lib/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld: error: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o: unsupported reloc 42 against global symbol main
          /usr/lib/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld: error: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o: unsupported reloc 41 against global symbol __libc_start_main
          /usr/lib/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld: error: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crti.o: unsupported reloc 42 against global symbol __gmon_start__
          /usr/lib/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld: error: /usr/lib/gcc/x86_64-linux-gnu/8/crtbeginS.o: unsupported reloc 42 against global symbol _ITM_deregisterTMCloneTable
          /usr/lib/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ld: error: /usr/lib/gcc/x86_64-linux-gnu/8/crtbeginS.o: unsupported reloc 42 against global symbol _ITM_registerTMCloneTable
          /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crti.o(.init+0x7): error: unsupported reloc 42
          /usr/lib/gcc/x86_64-linux-gnu/8/crtbeginS.o(.text+0x16): error: unsupported reloc 42
          /usr/lib/gcc/x86_64-linux-gnu/8/crtbeginS.o(.text+0x57): error: unsupported reloc 42
          /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o:function _start: error: unsupported reloc 42
          /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o:function _start: error: unsupported reloc 42
          /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o:function _start: error: unsupported reloc 42
          /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o:function _start: error: unsupported reloc 41
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `libc`.
warning: build failed, waiting for other jobs to finish...
error: build failed
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/__main__.py", line 17, in <module>
    main()
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/__main__.py", line 11, in main
    sys.exit(run_cli())
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/cli.py", line 132, in run_cli
    x.generate(x.output_dir)
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/gen/android.py", line 145, in generate
    self.build(base, tree_id, self.is_release)
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/gen/android.py", line 418, in build
    os.path.join(jni_dir, "libdivvunspell.so"),
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: './deps/giella-ime/../hfst-ospell-rs/target/armv7-linux-androideabi/release/libdivvunspell.so'
```

For reference, the project file is:

```
internalName: cuicateco_keyboard

locales:
  en:
    name: "Keyboard for Cuicatec"
    description: "A test keyboard for Cuicatec."
  es: 
    name: &bundleName "Un teclado para la lengua cuicateca"
    description: "Esto es un teclado diseñado para las varias propuestas ortográficas de la lengua cuicateca."

author: Francis M. Tyers
email: ftyers@iu.edu

layouts: [cux]

version: "1.0"
build: "1"

targets:
  android:
    packageId: so.ftyers.keyboards.cuicateco
    #icon: cuicateco-icon.pdf
    keyStore: /Users/ftyers/source/giellatekno/giella-core/kbdgen/cuicateco_keyboard.keystore
    keyAlias: cuicateco_keyboard

  osx: 
    packageId: so.ftyers.cuicateco
    codeSignId: "OSX"
    provisioningProfileId: Test

```

And the keyboard is:

```
internalName: cuicatec

displayNames:
  cux: Cuicatec
  en: Cuicatec
  es: Cuicateco 

locale: cux

locales: cux

modes:
  mobile-default: |
    ʼ w e r t y u i o p
    a s d f g h j k l ñ
    z x v b n m 
  mobile-shift: |
    ʼ W E R T Y U I O P 
    A S D F G H J K L Ñ
    Z X V B N M 

decimal: ','

deadKeys:
  iso-default: ["`"]
  iso-shift: ["`"]

longpress:
  A: Á À Ä A̱
  E: É À Ë E̱   
  I: Í Ì Ï I̱̱
  O: Ó Ò Ö O̱
  U: Ú Ù Ü U̱
  ʼ: q Q
  a: á à ä a̱
  e: é à ë e̱   
  i: í ì ï i̱̱
  o: ó ò ö o̱
  u: ú ù ü u̱

styles:
  tablet:
    actions:
      backspace: [1, right, fill]
      enter: [2, right, fill]
      shift: [3, both, fill]
  phone:
    actions:
      shift: [3, left, fill]
      backspace: [3, right, fill]

#targets:
#  android:
#    minimumSdk: 21

strings:
  space: gaske
  return: linnjámolsun

```
